"use client";

import React from "react";
import { motion } from "framer-motion";
import { ShieldCheck, Leaf, Zap, Globe2 } from "lucide-react";

const whyUsPoints = [
  {
    title: "100% CPCB Audit Security",
    description: "Every credit certificate and Form-6 manifest generated by EnviroServe is fully backed by real-world physical material recycling ledgers.",
    icon: ShieldCheck,
  },
  {
    title: "Zero-Landfill Mandate",
    description: "We divert 100% of hazardous components away from landfills, reclaiming precious secondary raw materials for manufacturing.",
    icon: Leaf,
  },
  {
    title: "Rapid Turnaround Execution",
    description: "Our dedicated portal specialists process registration documentation and EPR credit transfers well ahead of mandatory regulatory cutoffs.",
    icon: Zap,
  },
  {
    title: "Pan-India Logistics Capability",
    description: "Equipped with hazardous-certified transport logistics for bulk enterprise pickups across all Indian states and Union Territories.",
    icon: Globe2,
  },
];

export function WhyEnviroServe() {
  return (
    <section className="py-20 bg-slate-50 border-t border-slate-200/60">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <div className="text-center max-w-3xl mx-auto space-y-4 mb-16">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-enviro-light text-enviro-green text-xs font-bold uppercase tracking-wider">
            <span>Corporate Excellence</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-enviro-navy tracking-tight">
            Why Leading Enterprises Trust EnviroServe
          </h2>
          <p className="text-base text-enviro-gray">
            We bridge the gap between complex government environmental regulations and practical corporate operational needs.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {whyUsPoints.map((point, idx) => {
            const Icon = point.icon;
            return (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: idx * 0.1 }}
                className="bg-white p-6 rounded-2xl border border-slate-200/80 shadow-card hover:shadow-card-hover transition-all duration-300 space-y-4"
              >
                <div className="w-12 h-12 rounded-xl bg-enviro-light text-enviro-green flex items-center justify-center">
                  <Icon className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-bold text-enviro-navy">
                  {point.title}
                </h3>
                <p className="text-xs sm:text-sm text-enviro-gray leading-relaxed">
                  {point.description}
                </p>
              </motion.div>
            );
          })}
        </div>

      </div>
    </section>
  );
}
